name: Supabase Migrations Check

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "supabase/migrations/**"
      # - "supabase/seed.sql" # (opcional) inclua se quiser

jobs:
  lint-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Lint SQL
        run: supabase db lint
