name: Supabase Migrations Check

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "supabase/migrations/**"

jobs:
  lint-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Check SQL syntax only
        run: supabase db lint --schema-only
