name: Supabase Migrations (prod - simples)

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/migrations/**"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply migrations to PROD (URL direta)
        env:
          SUPABASE_DB_URL_PROD: ${{ secrets.SUPABASE_DB_URL_PROD }}
        run: |
          # opcional: ver o plano antes
          # supabase db push --db-url "$SUPABASE_DB_URL_PROD" --dry-run --debug
          supabase db push --db-url "$SUPABASE_DB_URL_PROD" --include-all
