# .github/workflows/supabase-migrate-prod.yml
name: Supabase Migrations Completed (prod)

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/migrations/**"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply migrations to PROD (via --db-url)
        env:
          SUPABASE_DB_URL_PROD: ${{ secrets.SUPABASE_DB_URL_PROD }}
        run: |
          if [ -z "${SUPABASE_DB_URL_PROD}" ]; then
            echo "❌ SUPABASE_DB_URL_PROD não definido nos Secrets."
            exit 1
          fi

          # opcional: prévia do plano
          # supabase db push --db-url "$SUPABASE_DB_URL_PROD" --dry-run

          supabase db push --db-url "$SUPABASE_DB_URL_PROD" --include-all
          echo "✅ Migrations completed (aplicadas em PROD)." >> $GITHUB_STEP_SUMMARY
