name: Apply Supabase Migrations (staging)

on:
  push:
    branches: [ "develop" ]

env:
  SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF_STG }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase link --project-ref $SUPABASE_PROJECT_REF

      - name: Apply migrations
        run: supabase db push --linked
