import type {
  ActivityRecord,
  AttentionBoxReadRecord,
  AttentionBoxRecord,
  CadenceAssignmentRecord,
  ContactQualityRecord,
  ContactRecord,
  DashboardMember,
  DashboardTeam,
  GoalProgressSnapshot,
  LeadRecord,
  MeetingRecord,
  MicrositeSnapshot,
  MicrositeVisitRecord,
  SaleRecord,
} from "./types";

export const DASHBOARD_ORG_ID = "org-demo-001";
export const CURRENT_OWNER_ID = "member-owner-joao";

const now = new Date();

function setTime(date: Date, hours: number, minutes = 0) {
  const copy = new Date(date);
  copy.setHours(hours, minutes, 0, 0);
  return copy;
}

function daysAgoIso(days: number, hours = 10, minutes = 0) {
  const base = new Date(now);
  base.setDate(base.getDate() - days);
  return setTime(base, hours, minutes).toISOString();
}

function daysAheadIso(days: number, hours = 10, minutes = 0) {
  const base = new Date(now);
  base.setDate(base.getDate() + days);
  return setTime(base, hours, minutes).toISOString();
}

const monthStart = setTime(new Date(now.getFullYear(), now.getMonth(), 1), 8);
const monthEnd = setTime(new Date(now.getFullYear(), now.getMonth() + 1, 0), 23, 59);

export const DASHBOARD_MEMBERS: DashboardMember[] = [
  { id: CURRENT_OWNER_ID, name: "João Martins", role: "owner", teamId: "team-gtm" },
  { id: "member-leader-ana", name: "Ana Prado", role: "leader", teamId: "team-sul", leaderId: CURRENT_OWNER_ID },
  { id: "member-leader-carlos", name: "Carlos Nogueira", role: "leader", teamId: "team-norte", leaderId: CURRENT_OWNER_ID },
  { id: "member-rep-paula", name: "Paula Ribeiro", role: "rep", teamId: "team-sul", leaderId: "member-leader-ana" },
  { id: "member-rep-helena", name: "Helena Dias", role: "rep", teamId: "team-sul", leaderId: "member-leader-ana" },
  { id: "member-rep-marcos", name: "Marcos Lima", role: "rep", teamId: "team-norte", leaderId: "member-leader-carlos" },
  { id: "member-rep-livia", name: "Lívia Costa", role: "rep", teamId: "team-norte", leaderId: "member-leader-carlos" },
];

export const DASHBOARD_TEAMS: DashboardTeam[] = [
  {
    id: "team-gtm",
    name: "Equipe GTM",
    leaderId: CURRENT_OWNER_ID,
    memberIds: [CURRENT_OWNER_ID, "member-leader-ana", "member-leader-carlos"],
  },
  {
    id: "team-sul",
    name: "Squad Sul",
    leaderId: "member-leader-ana",
    memberIds: ["member-leader-ana", "member-rep-paula", "member-rep-helena"],
  },
  {
    id: "team-norte",
    name: "Squad Norte",
    leaderId: "member-leader-carlos",
    memberIds: ["member-leader-carlos", "member-rep-marcos", "member-rep-livia"],
  },
];

export const LEADS: LeadRecord[] = [
  {
    id: "lead-001",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    source: "microsite",
    createdAt: daysAgoIso(2, 9),
    contactedAt: daysAgoIso(2, 11),
    respondedAt: daysAgoIso(2, 17),
    contactId: "contact-001",
  },
  {
    id: "lead-002",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    source: "whatsapp",
    createdAt: daysAgoIso(5, 10),
    contactedAt: daysAgoIso(5, 12),
    respondedAt: daysAgoIso(5, 14),
    contactId: "contact-002",
  },
  {
    id: "lead-003",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    source: "microsite",
    createdAt: daysAgoIso(8, 15),
    contactedAt: daysAgoIso(8, 17),
    respondedAt: daysAgoIso(6, 18),
    contactId: "contact-003",
  },
  {
    id: "lead-004",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    source: "event",
    createdAt: daysAgoIso(1, 9, 30),
    contactedAt: daysAgoIso(1, 11),
    respondedAt: daysAgoIso(1, 13),
    contactId: "contact-004",
  },
  {
    id: "lead-005",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    source: "microsite",
    createdAt: daysAgoIso(15, 16),
    contactedAt: daysAgoIso(15, 17),
    respondedAt: daysAgoIso(14, 18),
    contactId: "contact-005",
  },
  {
    id: "lead-006",
    ownerId: "member-rep-helena",
    teamId: "team-sul",
    source: "whatsapp",
    createdAt: daysAgoIso(3, 10),
    contactedAt: daysAgoIso(3, 11),
    respondedAt: daysAgoIso(2, 10),
    contactId: "contact-006",
  },
  {
    id: "lead-007",
    ownerId: "member-rep-helena",
    teamId: "team-sul",
    source: "microsite",
    createdAt: daysAgoIso(11, 14),
    contactedAt: daysAgoIso(11, 16),
    respondedAt: daysAgoIso(10, 18),
    contactId: "contact-007",
  },
  {
    id: "lead-008",
    ownerId: "member-rep-helena",
    teamId: "team-sul",
    source: "import",
    createdAt: daysAgoIso(4, 9),
    contactedAt: daysAgoIso(4, 10),
    respondedAt: undefined,
  },
  {
    id: "lead-009",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    source: "microsite",
    createdAt: daysAgoIso(2, 12),
    contactedAt: daysAgoIso(2, 13),
    respondedAt: daysAgoIso(2, 19),
    contactId: "contact-009",
  },
  {
    id: "lead-010",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    source: "event",
    createdAt: daysAgoIso(6, 9),
    contactedAt: daysAgoIso(6, 10),
    respondedAt: daysAgoIso(5, 12),
    contactId: "contact-010",
  },
  {
    id: "lead-011",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    source: "whatsapp",
    createdAt: daysAgoIso(9, 11),
    contactedAt: daysAgoIso(9, 12),
    respondedAt: daysAgoIso(9, 14),
    contactId: "contact-011",
  },
  {
    id: "lead-012",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    source: "microsite",
    createdAt: daysAgoIso(28, 9),
    contactedAt: daysAgoIso(28, 10),
    respondedAt: daysAgoIso(27, 10),
    contactId: "contact-012",
  },
  {
    id: "lead-013",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    source: "microsite",
    createdAt: daysAgoIso(1, 8),
    contactedAt: daysAgoIso(1, 10),
    respondedAt: daysAgoIso(1, 12),
    contactId: "contact-013",
  },
  {
    id: "lead-014",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    source: "whatsapp",
    createdAt: daysAgoIso(12, 13),
    contactedAt: daysAgoIso(12, 15),
    respondedAt: daysAgoIso(11, 17),
    contactId: "contact-014",
  },
  {
    id: "lead-015",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    source: "import",
    createdAt: daysAgoIso(7, 10),
    contactedAt: daysAgoIso(7, 13),
    respondedAt: undefined,
  },
  {
    id: "lead-016",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    source: "event",
    createdAt: daysAgoIso(32, 10),
    contactedAt: daysAgoIso(32, 11),
    respondedAt: daysAgoIso(31, 13),
    contactId: "contact-016",
  },
];

export const CONTACTS: ContactRecord[] = [
  {
    id: "contact-001",
    leadId: "lead-001",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    createdAt: daysAgoIso(2, 18),
    lastActivityAt: daysAgoIso(1, 16),
  },
  {
    id: "contact-002",
    leadId: "lead-002",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    createdAt: daysAgoIso(4, 13),
    lastActivityAt: daysAgoIso(2, 9),
  },
  {
    id: "contact-003",
    leadId: "lead-003",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    createdAt: daysAgoIso(6, 9),
    lastActivityAt: daysAgoIso(4, 11),
  },
  {
    id: "contact-004",
    leadId: "lead-004",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    createdAt: daysAgoIso(1, 14),
    lastActivityAt: daysAgoIso(0, 10),
  },
  {
    id: "contact-005",
    leadId: "lead-005",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    createdAt: daysAgoIso(14, 18),
    lastActivityAt: daysAgoIso(8, 9),
  },
  {
    id: "contact-006",
    leadId: "lead-006",
    ownerId: "member-rep-helena",
    teamId: "team-sul",
    createdAt: daysAgoIso(2, 12),
    lastActivityAt: daysAgoIso(1, 15),
  },
  {
    id: "contact-007",
    leadId: "lead-007",
    ownerId: "member-rep-helena",
    teamId: "team-sul",
    createdAt: daysAgoIso(9, 10),
    lastActivityAt: daysAgoIso(7, 13),
  },
  {
    id: "contact-008",
    ownerId: "member-rep-helena",
    teamId: "team-sul",
    createdAt: daysAgoIso(20, 11),
    lastActivityAt: daysAgoIso(15, 12),
  },
  {
    id: "contact-009",
    leadId: "lead-009",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    createdAt: daysAgoIso(1, 15),
    lastActivityAt: daysAgoIso(0, 11),
  },
  {
    id: "contact-010",
    leadId: "lead-010",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    createdAt: daysAgoIso(5, 15),
    lastActivityAt: daysAgoIso(3, 17),
  },
  {
    id: "contact-011",
    leadId: "lead-011",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    createdAt: daysAgoIso(8, 13),
    lastActivityAt: daysAgoIso(6, 15),
  },
  {
    id: "contact-012",
    leadId: "lead-012",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    createdAt: daysAgoIso(26, 10),
    lastActivityAt: daysAgoIso(22, 12),
  },
  {
    id: "contact-013",
    leadId: "lead-013",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    createdAt: daysAgoIso(1, 16),
    lastActivityAt: daysAgoIso(0, 9),
  },
  {
    id: "contact-014",
    leadId: "lead-014",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    createdAt: daysAgoIso(10, 15),
    lastActivityAt: daysAgoIso(6, 10),
  },
  {
    id: "contact-015",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    createdAt: daysAgoIso(40, 12),
    lastActivityAt: daysAgoIso(30, 9),
  },
  {
    id: "contact-016",
    leadId: "lead-016",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    createdAt: daysAgoIso(30, 13),
    lastActivityAt: daysAgoIso(29, 14),
  },
];

export const MEETINGS: MeetingRecord[] = [
  {
    id: "meeting-001",
    leadId: "lead-001",
    organizerId: "member-rep-paula",
    teamId: "team-sul",
    status: "completed",
    scheduledAt: daysAgoIso(1, 14),
  },
  {
    id: "meeting-002",
    leadId: "lead-003",
    organizerId: "member-rep-paula",
    teamId: "team-sul",
    status: "completed",
    scheduledAt: daysAgoIso(5, 16),
  },
  {
    id: "meeting-003",
    leadId: "lead-006",
    organizerId: "member-rep-helena",
    teamId: "team-sul",
    status: "registered",
    scheduledAt: daysAgoIso(0, 17),
  },
  {
    id: "meeting-004",
    leadId: "lead-007",
    organizerId: "member-rep-helena",
    teamId: "team-sul",
    status: "completed",
    scheduledAt: daysAgoIso(7, 11),
  },
  {
    id: "meeting-005",
    leadId: "lead-009",
    organizerId: "member-rep-marcos",
    teamId: "team-norte",
    status: "completed",
    scheduledAt: daysAgoIso(1, 10),
  },
  {
    id: "meeting-006",
    leadId: "lead-010",
    organizerId: "member-rep-marcos",
    teamId: "team-norte",
    status: "completed",
    scheduledAt: daysAgoIso(3, 15),
  },
  {
    id: "meeting-007",
    leadId: "lead-011",
    organizerId: "member-rep-marcos",
    teamId: "team-norte",
    status: "no_show",
    scheduledAt: daysAgoIso(4, 9),
  },
  {
    id: "meeting-008",
    leadId: "lead-013",
    organizerId: "member-rep-livia",
    teamId: "team-norte",
    status: "registered",
    scheduledAt: daysAgoIso(0, 19),
  },
  {
    id: "meeting-009",
    leadId: "lead-014",
    organizerId: "member-rep-livia",
    teamId: "team-norte",
    status: "completed",
    scheduledAt: daysAgoIso(8, 10),
  },
];

export const SALES: SaleRecord[] = [
  {
    id: "sale-001",
    leadId: "lead-003",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    closedAt: daysAgoIso(4, 18),
    amount: 12500,
  },
  {
    id: "sale-002",
    leadId: "lead-009",
    ownerId: "member-rep-marcos",
    teamId: "team-norte",
    closedAt: daysAgoIso(1, 18),
    amount: 9800,
  },
  {
    id: "sale-003",
    leadId: "lead-014",
    ownerId: "member-rep-livia",
    teamId: "team-norte",
    closedAt: daysAgoIso(6, 19),
    amount: 11200,
  },
  {
    id: "sale-004",
    ownerId: "member-rep-paula",
    teamId: "team-sul",
    closedAt: daysAgoIso(20, 16),
    amount: 7500,
  },
];

export const ACTIVITIES: ActivityRecord[] = [
  // Recent day activities (heatmap focus)
  { id: "activity-001", memberId: "member-rep-paula", teamId: "team-sul", type: "whatsapp", timestamp: daysAgoIso(0, 9) },
  { id: "activity-002", memberId: "member-rep-paula", teamId: "team-sul", type: "lead_created", timestamp: daysAgoIso(0, 10) },
  { id: "activity-003", memberId: "member-rep-paula", teamId: "team-sul", type: "meeting", timestamp: daysAgoIso(0, 14) },
  { id: "activity-004", memberId: "member-rep-helena", teamId: "team-sul", type: "whatsapp", timestamp: daysAgoIso(0, 12) },
  { id: "activity-005", memberId: "member-rep-helena", teamId: "team-sul", type: "microsite", timestamp: daysAgoIso(0, 16) },
  { id: "activity-006", memberId: "member-rep-marcos", teamId: "team-norte", type: "lead_created", timestamp: daysAgoIso(0, 9, 30) },
  { id: "activity-007", memberId: "member-rep-marcos", teamId: "team-norte", type: "meeting", timestamp: daysAgoIso(0, 15) },
  { id: "activity-008", memberId: "member-rep-livia", teamId: "team-norte", type: "whatsapp", timestamp: daysAgoIso(0, 18) },
  // Previous days
  { id: "activity-009", memberId: "member-rep-paula", teamId: "team-sul", type: "lead_created", timestamp: daysAgoIso(1, 9) },
  { id: "activity-010", memberId: "member-rep-paula", teamId: "team-sul", type: "cadence", timestamp: daysAgoIso(1, 11) },
  { id: "activity-011", memberId: "member-rep-helena", teamId: "team-sul", type: "meeting", timestamp: daysAgoIso(1, 17) },
  { id: "activity-012", memberId: "member-rep-marcos", teamId: "team-norte", type: "whatsapp", timestamp: daysAgoIso(1, 13) },
  { id: "activity-013", memberId: "member-rep-livia", teamId: "team-norte", type: "meeting", timestamp: daysAgoIso(1, 10) },
  { id: "activity-014", memberId: "member-rep-paula", teamId: "team-sul", type: "lead_created", timestamp: daysAgoIso(2, 9) },
  { id: "activity-015", memberId: "member-rep-paula", teamId: "team-sul", type: "microsite", timestamp: daysAgoIso(2, 19) },
  { id: "activity-016", memberId: "member-rep-helena", teamId: "team-sul", type: "whatsapp", timestamp: daysAgoIso(2, 8) },
  { id: "activity-017", memberId: "member-rep-marcos", teamId: "team-norte", type: "meeting", timestamp: daysAgoIso(2, 17) },
  { id: "activity-018", memberId: "member-rep-livia", teamId: "team-norte", type: "lead_created", timestamp: daysAgoIso(2, 10) },
  { id: "activity-019", memberId: "member-rep-paula", teamId: "team-sul", type: "whatsapp", timestamp: daysAgoIso(3, 9) },
  { id: "activity-020", memberId: "member-rep-helena", teamId: "team-sul", type: "lead_created", timestamp: daysAgoIso(3, 14) },
  { id: "activity-021", memberId: "member-rep-marcos", teamId: "team-norte", type: "cadence", timestamp: daysAgoIso(3, 15) },
  { id: "activity-022", memberId: "member-rep-livia", teamId: "team-norte", type: "whatsapp", timestamp: daysAgoIso(3, 19) },
  { id: "activity-023", memberId: "member-rep-paula", teamId: "team-sul", type: "meeting", timestamp: daysAgoIso(4, 11) },
  { id: "activity-024", memberId: "member-rep-helena", teamId: "team-sul", type: "microsite", timestamp: daysAgoIso(4, 18) },
  { id: "activity-025", memberId: "member-rep-marcos", teamId: "team-norte", type: "whatsapp", timestamp: daysAgoIso(4, 13) },
  { id: "activity-026", memberId: "member-rep-livia", teamId: "team-norte", type: "meeting", timestamp: daysAgoIso(4, 9) },
  { id: "activity-027", memberId: "member-rep-paula", teamId: "team-sul", type: "lead_created", timestamp: daysAgoIso(5, 10) },
  { id: "activity-028", memberId: "member-rep-helena", teamId: "team-sul", type: "whatsapp", timestamp: daysAgoIso(5, 13) },
  { id: "activity-029", memberId: "member-rep-marcos", teamId: "team-norte", type: "lead_created", timestamp: daysAgoIso(5, 9) },
  { id: "activity-030", memberId: "member-rep-livia", teamId: "team-norte", type: "microsite", timestamp: daysAgoIso(5, 18) },
  { id: "activity-031", memberId: "member-rep-paula", teamId: "team-sul", type: "cadence", timestamp: daysAgoIso(6, 16) },
  { id: "activity-032", memberId: "member-rep-helena", teamId: "team-sul", type: "meeting", timestamp: daysAgoIso(6, 17) },
  { id: "activity-033", memberId: "member-rep-marcos", teamId: "team-norte", type: "whatsapp", timestamp: daysAgoIso(6, 8) },
  { id: "activity-034", memberId: "member-rep-livia", teamId: "team-norte", type: "lead_created", timestamp: daysAgoIso(6, 14) },
  { id: "activity-035", memberId: "member-rep-paula", teamId: "team-sul", type: "lead_created", timestamp: daysAgoIso(7, 9) },
  { id: "activity-036", memberId: "member-rep-helena", teamId: "team-sul", type: "whatsapp", timestamp: daysAgoIso(7, 11) },
  { id: "activity-037", memberId: "member-rep-marcos", teamId: "team-norte", type: "meeting", timestamp: daysAgoIso(7, 15) },
  { id: "activity-038", memberId: "member-rep-livia", teamId: "team-norte", type: "whatsapp", timestamp: daysAgoIso(7, 18) },
  { id: "activity-039", memberId: "member-rep-paula", teamId: "team-sul", type: "cadence", timestamp: daysAgoIso(8, 10) },
  { id: "activity-040", memberId: "member-rep-helena", teamId: "team-sul", type: "lead_created", timestamp: daysAgoIso(8, 12) },
  { id: "activity-041", memberId: "member-rep-marcos", teamId: "team-norte", type: "meeting", timestamp: daysAgoIso(8, 17) },
  { id: "activity-042", memberId: "member-rep-livia", teamId: "team-norte", type: "microsite", timestamp: daysAgoIso(8, 9) },
];

export const MICROSITES: MicrositeSnapshot[] = [
  {
    id: "microsite-sul-energia",
    slug: "energia-sul",
    title: "Energia Sul",
    teamId: "team-sul",
    visits: 840,
    leads: 112,
    topRepId: "member-rep-paula",
    topRepLeads: 58,
    updatedAt: daysAgoIso(0, 20),
  },
  {
    id: "microsite-norte-agro",
    slug: "agro-norte",
    title: "Agro Norte",
    teamId: "team-norte",
    visits: 760,
    leads: 96,
    topRepId: "member-rep-marcos",
    topRepLeads: 44,
    updatedAt: daysAgoIso(1, 18),
  },
  {
    id: "microsite-norte-tech",
    slug: "tech-norte",
    title: "Tech Norte",
    teamId: "team-norte",
    visits: 540,
    leads: 68,
    topRepId: "member-rep-livia",
    topRepLeads: 36,
    updatedAt: daysAgoIso(2, 19),
  },
  {
    id: "microsite-sul-health",
    slug: "health-sul",
    title: "Health Sul",
    teamId: "team-sul",
    visits: 620,
    leads: 74,
    topRepId: "member-rep-helena",
    topRepLeads: 33,
    updatedAt: daysAgoIso(0, 21),
  },
];

export const MICROSITE_VISITS_DAILY: MicrositeVisitRecord[] = [
  { date: daysAgoIso(0, 7), teamId: "team-sul", visits: 92 },
  { date: daysAgoIso(1, 7), teamId: "team-sul", visits: 88 },
  { date: daysAgoIso(2, 7), teamId: "team-sul", visits: 94 },
  { date: daysAgoIso(3, 7), teamId: "team-sul", visits: 90 },
  { date: daysAgoIso(4, 7), teamId: "team-sul", visits: 85 },
  { date: daysAgoIso(5, 7), teamId: "team-sul", visits: 98 },
  { date: daysAgoIso(6, 7), teamId: "team-sul", visits: 96 },
  { date: daysAgoIso(7, 7), teamId: "team-sul", visits: 91 },
  { date: daysAgoIso(8, 7), teamId: "team-sul", visits: 93 },
  { date: daysAgoIso(9, 7), teamId: "team-sul", visits: 89 },
  { date: daysAgoIso(10, 7), teamId: "team-sul", visits: 87 },
  { date: daysAgoIso(11, 7), teamId: "team-sul", visits: 90 },
  { date: daysAgoIso(12, 7), teamId: "team-sul", visits: 94 },
  { date: daysAgoIso(13, 7), teamId: "team-sul", visits: 95 },
  { date: daysAgoIso(14, 7), teamId: "team-sul", visits: 88 },
  { date: daysAgoIso(15, 7), teamId: "team-sul", visits: 86 },
  { date: daysAgoIso(16, 7), teamId: "team-sul", visits: 84 },
  { date: daysAgoIso(17, 7), teamId: "team-sul", visits: 90 },
  { date: daysAgoIso(18, 7), teamId: "team-sul", visits: 92 },
  { date: daysAgoIso(19, 7), teamId: "team-sul", visits: 93 },
  { date: daysAgoIso(20, 7), teamId: "team-sul", visits: 91 },
  { date: daysAgoIso(21, 7), teamId: "team-sul", visits: 88 },
  { date: daysAgoIso(22, 7), teamId: "team-sul", visits: 90 },
  { date: daysAgoIso(23, 7), teamId: "team-sul", visits: 94 },
  { date: daysAgoIso(24, 7), teamId: "team-sul", visits: 89 },
  { date: daysAgoIso(25, 7), teamId: "team-sul", visits: 87 },
  { date: daysAgoIso(26, 7), teamId: "team-sul", visits: 88 },
  { date: daysAgoIso(27, 7), teamId: "team-sul", visits: 92 },
  { date: daysAgoIso(28, 7), teamId: "team-sul", visits: 86 },
  { date: daysAgoIso(29, 7), teamId: "team-sul", visits: 83 },
  { date: daysAgoIso(0, 7), teamId: "team-norte", visits: 84 },
  { date: daysAgoIso(1, 7), teamId: "team-norte", visits: 82 },
  { date: daysAgoIso(2, 7), teamId: "team-norte", visits: 86 },
  { date: daysAgoIso(3, 7), teamId: "team-norte", visits: 80 },
  { date: daysAgoIso(4, 7), teamId: "team-norte", visits: 79 },
  { date: daysAgoIso(5, 7), teamId: "team-norte", visits: 85 },
  { date: daysAgoIso(6, 7), teamId: "team-norte", visits: 87 },
  { date: daysAgoIso(7, 7), teamId: "team-norte", visits: 83 },
  { date: daysAgoIso(8, 7), teamId: "team-norte", visits: 82 },
  { date: daysAgoIso(9, 7), teamId: "team-norte", visits: 81 },
  { date: daysAgoIso(10, 7), teamId: "team-norte", visits: 80 },
  { date: daysAgoIso(11, 7), teamId: "team-norte", visits: 84 },
  { date: daysAgoIso(12, 7), teamId: "team-norte", visits: 86 },
  { date: daysAgoIso(13, 7), teamId: "team-norte", visits: 85 },
  { date: daysAgoIso(14, 7), teamId: "team-norte", visits: 78 },
  { date: daysAgoIso(15, 7), teamId: "team-norte", visits: 79 },
  { date: daysAgoIso(16, 7), teamId: "team-norte", visits: 81 },
  { date: daysAgoIso(17, 7), teamId: "team-norte", visits: 80 },
  { date: daysAgoIso(18, 7), teamId: "team-norte", visits: 83 },
  { date: daysAgoIso(19, 7), teamId: "team-norte", visits: 84 },
  { date: daysAgoIso(20, 7), teamId: "team-norte", visits: 82 },
  { date: daysAgoIso(21, 7), teamId: "team-norte", visits: 79 },
  { date: daysAgoIso(22, 7), teamId: "team-norte", visits: 78 },
  { date: daysAgoIso(23, 7), teamId: "team-norte", visits: 80 },
  { date: daysAgoIso(24, 7), teamId: "team-norte", visits: 82 },
  { date: daysAgoIso(25, 7), teamId: "team-norte", visits: 77 },
  { date: daysAgoIso(26, 7), teamId: "team-norte", visits: 79 },
  { date: daysAgoIso(27, 7), teamId: "team-norte", visits: 81 },
  { date: daysAgoIso(28, 7), teamId: "team-norte", visits: 76 },
  { date: daysAgoIso(29, 7), teamId: "team-norte", visits: 75 },
];

export const CADENCE_ASSIGNMENTS: CadenceAssignmentRecord[] = [
  {
    id: "assignment-ignite-paula",
    cadenceId: "cadence-ignite",
    cadenceName: "Ignite WhatsApp",
    memberId: "member-rep-paula",
    teamId: "team-sul",
    dueSteps: 32,
    completedSteps: 29,
    overdueSteps: 2,
    periodStart: monthStart.toISOString(),
    periodEnd: monthEnd.toISOString(),
  },
  {
    id: "assignment-ignite-helena",
    cadenceId: "cadence-ignite",
    cadenceName: "Ignite WhatsApp",
    memberId: "member-rep-helena",
    teamId: "team-sul",
    dueSteps: 28,
    completedSteps: 22,
    overdueSteps: 4,
    periodStart: monthStart.toISOString(),
    periodEnd: monthEnd.toISOString(),
  },
  {
    id: "assignment-nurture-marcos",
    cadenceId: "cadence-nurture",
    cadenceName: "Nurture Leads",
    memberId: "member-rep-marcos",
    teamId: "team-norte",
    dueSteps: 30,
    completedSteps: 27,
    overdueSteps: 1,
    periodStart: monthStart.toISOString(),
    periodEnd: monthEnd.toISOString(),
  },
  {
    id: "assignment-nurture-livia",
    cadenceId: "cadence-nurture",
    cadenceName: "Nurture Leads",
    memberId: "member-rep-livia",
    teamId: "team-norte",
    dueSteps: 24,
    completedSteps: 18,
    overdueSteps: 3,
    periodStart: monthStart.toISOString(),
    periodEnd: monthEnd.toISOString(),
  },
  {
    id: "assignment-outbound-ana",
    cadenceId: "cadence-outbound",
    cadenceName: "Outbound Enterprise",
    memberId: "member-leader-ana",
    teamId: "team-sul",
    dueSteps: 16,
    completedSteps: 15,
    overdueSteps: 0,
    periodStart: monthStart.toISOString(),
    periodEnd: monthEnd.toISOString(),
  },
];

export const GOAL_SNAPSHOTS: GoalProgressSnapshot[] = [
  {
    id: "goal-paula",
    memberId: "member-rep-paula",
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`,
    contactsTarget: 40,
    contactsAchieved: 34,
    meetingsTarget: 16,
    meetingsAchieved: 14,
    salesTarget: 8,
    salesAchieved: 6,
    lastUpdatedAt: daysAgoIso(0, 11),
  },
  {
    id: "goal-helena",
    memberId: "member-rep-helena",
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`,
    contactsTarget: 32,
    contactsAchieved: 24,
    meetingsTarget: 12,
    meetingsAchieved: 9,
    salesTarget: 6,
    salesAchieved: 4,
    lastUpdatedAt: daysAgoIso(1, 15),
  },
  {
    id: "goal-marcos",
    memberId: "member-rep-marcos",
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`,
    contactsTarget: 36,
    contactsAchieved: 31,
    meetingsTarget: 14,
    meetingsAchieved: 12,
    salesTarget: 7,
    salesAchieved: 5,
    lastUpdatedAt: daysAgoIso(0, 10),
  },
  {
    id: "goal-livia",
    memberId: "member-rep-livia",
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`,
    contactsTarget: 36,
    contactsAchieved: 28,
    meetingsTarget: 14,
    meetingsAchieved: 11,
    salesTarget: 7,
    salesAchieved: 6,
    lastUpdatedAt: daysAgoIso(0, 18),
  },
  {
    id: "goal-ana",
    memberId: "member-leader-ana",
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`,
    contactsTarget: 60,
    contactsAchieved: 48,
    meetingsTarget: 24,
    meetingsAchieved: 20,
    salesTarget: 10,
    salesAchieved: 8,
    lastUpdatedAt: daysAgoIso(2, 9),
  },
  {
    id: "goal-carlos",
    memberId: "member-leader-carlos",
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`,
    contactsTarget: 58,
    contactsAchieved: 46,
    meetingsTarget: 22,
    meetingsAchieved: 18,
    salesTarget: 9,
    salesAchieved: 7,
    lastUpdatedAt: daysAgoIso(2, 11),
  },
];

export const CONTACT_QUALITY: ContactQualityRecord[] = [
  { contactId: "contact-001", memberId: "member-rep-paula", teamId: "team-sul", daysSinceLastFollowup: 3, hasDuplicate: false },
  { contactId: "contact-002", memberId: "member-rep-paula", teamId: "team-sul", daysSinceLastFollowup: 6, hasDuplicate: false },
  { contactId: "contact-003", memberId: "member-rep-paula", teamId: "team-sul", daysSinceLastFollowup: 9, hasDuplicate: false },
  { contactId: "contact-004", memberId: "member-rep-paula", teamId: "team-sul", daysSinceLastFollowup: 1, hasDuplicate: false },
  { contactId: "contact-005", memberId: "member-rep-paula", teamId: "team-sul", daysSinceLastFollowup: 11, hasDuplicate: true },
  { contactId: "contact-006", memberId: "member-rep-helena", teamId: "team-sul", daysSinceLastFollowup: 2, hasDuplicate: false },
  { contactId: "contact-007", memberId: "member-rep-helena", teamId: "team-sul", daysSinceLastFollowup: 7, hasDuplicate: false },
  { contactId: "contact-008", memberId: "member-rep-helena", teamId: "team-sul", daysSinceLastFollowup: 18, hasDuplicate: true },
  { contactId: "contact-009", memberId: "member-rep-marcos", teamId: "team-norte", daysSinceLastFollowup: 1, hasDuplicate: false },
  { contactId: "contact-010", memberId: "member-rep-marcos", teamId: "team-norte", daysSinceLastFollowup: 3, hasDuplicate: false },
  { contactId: "contact-011", memberId: "member-rep-marcos", teamId: "team-norte", daysSinceLastFollowup: 5, hasDuplicate: false },
  { contactId: "contact-012", memberId: "member-rep-marcos", teamId: "team-norte", daysSinceLastFollowup: 15, hasDuplicate: false },
  { contactId: "contact-013", memberId: "member-rep-livia", teamId: "team-norte", daysSinceLastFollowup: 0, hasDuplicate: false },
  { contactId: "contact-014", memberId: "member-rep-livia", teamId: "team-norte", daysSinceLastFollowup: 6, hasDuplicate: false },
  { contactId: "contact-015", memberId: "member-rep-livia", teamId: "team-norte", daysSinceLastFollowup: 28, hasDuplicate: true },
  { contactId: "contact-016", memberId: "member-rep-livia", teamId: "team-norte", daysSinceLastFollowup: 13, hasDuplicate: false },
];

export const ATTENTION_BOXES_SEED: AttentionBoxRecord[] = [
  {
    id: "attention-pinned-ops",
    orgId: DASHBOARD_ORG_ID,
    title: "Checklist de cadências para o Quarter Kickoff",
    bodyMd:
      "**Prioridade:** revisar fluxos automáticos, validar templates de WhatsApp e confirmar responsáveis até sexta-feira.",
    variant: "warning",
    audience: "leaders",
    startAt: daysAgoIso(1, 8),
    endAt: daysAheadIso(5, 19),
    pinned: true,
    createdByMemberId: CURRENT_OWNER_ID,
    createdAt: daysAgoIso(3, 9),
    updatedAt: daysAgoIso(1, 9),
  },
  {
    id: "attention-info-target",
    orgId: DASHBOARD_ORG_ID,
    title: "Nova meta de conversão lead→contato",
    bodyMd:
      "A meta mínima sobe para **35%** neste mês. Use o drill-down de funil para localizar gargalos específicos.",
    variant: "info",
    audience: "org",
    startAt: daysAgoIso(4, 9),
    endAt: daysAheadIso(20, 20),
    pinned: false,
    createdByMemberId: CURRENT_OWNER_ID,
    createdAt: daysAgoIso(4, 9),
    updatedAt: daysAgoIso(4, 9),
  },
  {
    id: "attention-success-goals",
    orgId: DASHBOARD_ORG_ID,
    title: "70% da equipe bateu a meta de cadências",
    bodyMd: "Parabéns squad! Continuem marcando as tarefas como concluídas para manter o score.",
    variant: "success",
    audience: "leaders",
    startAt: daysAgoIso(6, 10),
    endAt: daysAheadIso(2, 18),
    pinned: false,
    createdByMemberId: CURRENT_OWNER_ID,
    createdAt: daysAgoIso(6, 10),
    updatedAt: daysAgoIso(2, 15),
  },
  {
    id: "attention-danger-dup",
    orgId: DASHBOARD_ORG_ID,
    title: "Duplicidades no mailing Agro Norte",
    bodyMd:
      "Foram detectados contatos duplicados na importação de ontem. Revise o relatório de *Qualidade de dados* e unifique os registros.",
    variant: "danger",
    audience: "custom",
    audienceMemberIds: ["member-leader-carlos", "member-rep-marcos"],
    startAt: daysAgoIso(0, 7),
    endAt: daysAheadIso(3, 21),
    pinned: true,
    createdByMemberId: CURRENT_OWNER_ID,
    createdAt: daysAgoIso(0, 7),
    updatedAt: daysAgoIso(0, 7),
  },
  {
    id: "attention-expired-expo",
    orgId: DASHBOARD_ORG_ID,
    title: "Expo Vendas finalizada",
    bodyMd: "Obrigado a todos pela presença. Consolidem os leads no funil até o final do dia.",
    variant: "info",
    audience: "org",
    startAt: daysAgoIso(12, 9),
    endAt: daysAgoIso(2, 19),
    pinned: false,
    createdByMemberId: CURRENT_OWNER_ID,
    createdAt: daysAgoIso(12, 9),
    updatedAt: daysAgoIso(2, 19),
  },
];

export const ATTENTION_BOX_READS_SEED: AttentionBoxReadRecord[] = [
  {
    attentionBoxId: "attention-info-target",
    memberId: "member-rep-paula",
    readAt: daysAgoIso(2, 12),
  },
  {
    attentionBoxId: "attention-info-target",
    memberId: "member-rep-marcos",
    readAt: daysAgoIso(1, 9),
  },
  {
    attentionBoxId: "attention-success-goals",
    memberId: "member-leader-ana",
    readAt: daysAgoIso(1, 10),
  },
];
